#!/usr/bin/env node
/**
 * MQT Review Seeder
 * Seeds 5–10 authentic-feeling Indian reviews per package into Supabase.
 * Uses service-role key to bypass RLS (runs locally only, never committed).
 *
 * RUN: node scripts/seed-reviews.js
 */

import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://pvvbyqoqbxkjcnlhybeo.supabase.co";
const SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2dmJ5cW9xYnhramNubGh5YmVvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTgzMTMxMywiZXhwIjoyMDkxNDA3MzEzfQ.GsvPO5nyDmAcEFP1pIToaXjGyJIdZx691P0Lq81rQDI";

const sb = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

// ─── Indian avatar base (DiceBear – realistic initials) ───────────────────
const avatar = (seed) =>
  `https://api.dicebear.com/8.x/initials/svg?seed=${encodeURIComponent(seed)}&backgroundColor=0369a1,047857,7c3aed,b45309,be123c,0f766e&fontFamily=Georgia&fontSize=40`;

// ─── Packages from DB ─────────────────────────────────────────────────────
const PACKAGES = [
  { id: "c8ffe251-f788-4a45-b6ad-68962ea02a4c", slug: "kashmir-honeymoon-5-nights-6-days",       title: "Kashmir Honeymoon Special" },
  { id: "4a4efd47-3e62-4b63-94c7-37817b4a1688", slug: "valley-of-flowers-trek-6-nights-7-days",  title: "Valley of Flowers Trek" },
  { id: "0a71e5d4-f4ee-47db-98f3-8651f4deb0f4", slug: "varanasi-spiritual-3-nights-4-days",      title: "Varanasi Spiritual Journey" },
  { id: "8604d4ea-e7fc-4ca4-b360-30d9eab6c081", slug: "manali-family-4-nights-5-days",           title: "Manali Family Adventure" },
  { id: "94d02f0b-0dba-4e4c-af07-2d55d9fd8672", slug: "rishikesh-adventure-2-nights-3-days",     title: "Rishikesh Adventure Escape" },
  { id: "fc5a127e-312d-42b6-a4ad-70c004d9d8e0", slug: "kashmir-family-7-nights-8-days",          title: "Kashmir Family Discovery" },
  { id: "5873338f-653b-429b-89cc-3a191b924e33", slug: "ladakh-luxury-8-nights-9-days",           title: "Ladakh Luxury Expedition" },
  { id: "a37e9304-a79d-4bdd-8599-54478b0ae978", slug: "char-dham-yatra-10-nights-11-days",       title: "Char Dham Yatra by Road" },
  { id: "bf906502-d381-4b3e-b2aa-1cef0ed8c481", slug: "kedarnath-helicopter-2-nights-3-days",    title: "Kedarnath Helicopter Package" },
  { id: "a4f1b7b1-1aff-4b87-993d-d1d9d2852c2d", slug: "manali-winter-snow-4-nights-5-days",     title: "Manali Winter Snow Package" },
  { id: "9a444907-0f5b-4d5c-a626-07d46209806b", slug: "kashmir-solo-4-nights-5-days",            title: "Kashmir Solo Explorer" },
  { id: "1bc34c50-4f08-4ab2-b37d-685269e6b908", slug: "varanasi-prayagraj-4-nights-5-days",     title: "Varanasi & Prayagraj Pilgrimage" },
  { id: "46a07f4e-8acd-4073-8710-cd30d10c9941", slug: "himalayan-grand-circuit-12-nights-13-days", title: "Himalayan Grand Circuit" },
  { id: "478c7c83-7775-4d6c-be30-1e6fda8eecdb", slug: "kedarnath-yatra-5-nights-6-days",         title: "Kedarnath Yatra Package" },
  { id: "1df56cea-4154-478e-a4dc-d90d0a4835c1", slug: "ladakh-adventure-7-nights-8-days",        title: "Ladakh Adventure Tour" },
];

// ─── Review bank per package ──────────────────────────────────────────────
// rating: 5 = 5★, 4 = 4★, 3 = 3★ (but stored as integer for DB constraint)
// Half-stars not supported by DB schema (SMALLINT 1-5), so we use 4 for 4★ and 3 for ~3.5★
const REVIEWS = {
  "kashmir-honeymoon-5-nights-6-days": [
    { name: "Priya Nair", rating: 5, title: "Literally a dream come true 🌸", content: "My husband and I were completely blown away. The houseboat on Dal Lake felt like we were in a Bollywood movie — minus the dramatic rain scene, thankfully! The MQT team had arranged fresh lotus flowers in our room, shikara rides at sunrise, and even a surprise candle-light dinner on the rooftop. The couple package is honestly worth every rupee. Will recommend to every newlywed couple I know.", days_ago: 12 },
    { name: "Arjun Kapoor", rating: 5, title: "Best honeymoon decision of our lives", content: "Booked this after reading several positive reviews and I can confirm — every word is true. Our coordinator Rahul ji was available 24/7 and genuinely cared about making our trip perfect. Gulmarg's gondola ride with snow-capped peaks behind my wife is a photo I'll frame forever. The hotels were premium and spotlessly clean. 10/10, no complaints.", days_ago: 25 },
    { name: "Sunita Sharma", rating: 5, title: "Kashmir is heaven and MQT made it even better", content: "As someone who was nervous about travelling so far for our honeymoon, the MyQuickTrippers team put all our anxiety to rest within the first 30 minutes. Our driver was punctual, friendly, and incredibly knowledgeable about local spots that aren't in any tourist guidebook. The tulip garden visit they arranged off-schedule was the highlight of the entire trip!", days_ago: 38 },
    { name: "Vikram Nambiar", rating: 4, title: "Beautiful experience, minor hiccup at check-in", content: "The package overall is fantastic — Kashmir's beauty is indescribable and MQT's curation is excellent. The only reason for 4 stars instead of 5 is that there was a 2-hour delay at hotel check-in in Pahalgam, which was apparently due to a local political bandh that nobody could have predicted. The team compensated with a lovely complimentary dinner. Still a very memorable honeymoon.", days_ago: 45 },
    { name: "Meera Krishnan", rating: 5, title: "Srinagar stole my heart forever", content: "I'm not the type to write reviews but this trip genuinely deserves one. The MQT coordinator remembered that I had mentioned I love vintage photography and actually arranged a visit to a heritage photographer's studio in old Srinagar. That level of personal attention is rare. Also the Wazwan food they arranged was authentic and incredible. Five stars isn't even enough.", days_ago: 60 },
    { name: "Rohit Desai", rating: 5, title: "Planned our 1st anniversary here — magical!", content: "Decided last minute and MQT pulled it together beautifully within 72 hours. The houseboats are absolutely gorgeous — ours had carved walnut wood interiors that smelled like cedar. Shikara ride in the early morning mist is something out of a National Geographic documentary. My wife literally cried happy tears at Mughal Gardens. Perfect trip.", days_ago: 72 },
    { name: "Deepika Menon", rating: 4, title: "Great trip, weather was unpredictable", content: "Kashmir was breathtaking and MQT handled everything professionally. We did face one overcast day in Pahalgam which limited visibility at Betaab Valley, but that's obviously nature's call and not something any travel company can control. The team quickly rescheduled the activities for the following morning and we caught the valley in beautiful golden light. Very adaptive and responsive team.", days_ago: 90 },
  ],

  "valley-of-flowers-trek-6-nights-7-days": [
    { name: "Anil Bhatia", rating: 5, title: "The rarest natural spectacle I've ever witnessed", content: "When they say Valley of Flowers looks like a painter's canvas, they are NOT exaggerating. 500+ species of wildflowers in full bloom and MQT's expert botanist guide who could name every single one. The trek itself is moderately challenging but the team had emergency oxygen cylinders and a medical kit which gave us complete peace of mind. Genuinely life-changing experience.", days_ago: 15 },
    { name: "Kavya Iyer", rating: 5, title: "As a solo female traveller, I felt completely safe", content: "I was apprehensive about trekking in a remote Himalayan valley alone but the MQT group tour had 8 people and 2 guides. Our lead guide Govind Singh has been trekking this route for 12 years and his knowledge of alpine ecology is phenomenal. The camping setup was cozy and hygienic. Hemkund Sahib ji's darshan was a spiritual moment I won't forget as long as I live.", days_ago: 22 },
    { name: "Sanjay Kulkarni", rating: 5, title: "Worth every minute of the journey", content: "The approach through Joshimath and Govindghat is itself scenic beyond belief. MQT had arranged premium sleeping bags and high-altitude tents. My favourite moment was waking up at 5am and stepping out to find the valley completely shrouded in mist with just the tops of the Himalayan peaks visible. Pure magic. Already planning to come back next year.", days_ago: 30 },
    { name: "Preethi Rajan", rating: 4, title: "Stunning but physically demanding — be prepared", content: "The Valley of Flowers absolutely delivers on every promise. However, I want to be honest — the trek is genuinely tough if you're not fit. I struggled on day 2 and MQT's backup team had a horse ready within 15 minutes without any extra charge. That safety net is what makes them stand out. The valley itself? Speechless. My phone camera simply cannot capture what your eyes see.", days_ago: 45 },
    { name: "Harish Nair", rating: 5, title: "Best Rs. I've ever spent on anything", content: "Retired professor here — trekked this at age 58 with MQT's careful pacing and I completed every single day. Their altitude acclimatisation protocol is scientific and practical. The botanical diversity in the valley is extraordinary for anyone with even a passing interest in plant life. MQT's guides will teach you more about Himalayan ecology than any university course.", days_ago: 55 },
    { name: "Ritu Agarwal", rating: 3, title: "Beautiful valley, tough entry logistics", content: "The valley itself deserves 5 stars without question — it's genuinely one of India's natural wonders. My rating is 3 because the monsoon season meant the approach road from Rishikesh had landslide-related diversions that added almost 4 hours to our first day journey. MQT communicated about this promptly and everyone was safe, but exhaustion set in before the trek even started. A risk of the season, not the company.", days_ago: 70 },
    { name: "Gaurav Malhotra", rating: 5, title: "UNESCO World Heritage Site at its most spectacular", content: "Third time trekking to Valley of Flowers and first time with MQT — and I wish I had done it with them from the start. The quality of the camping food alone is worth the premium. Freshly cooked dal, rice and sabzi at high altitude in a remote valley tastes better than 5-star hotel food, trust me.", days_ago: 80 },
  ],

  "varanasi-spiritual-3-nights-4-days": [
    { name: "Sudha Murthy", rating: 5, title: "Ganga Aarti will change how you see life", content: "I've been to Varanasi twice before but always hated the chaotic ghat experience. MQT arranged a private boat with a wonderful priest who explained every ritual during the Ganga Aarti. Watching 51 diyas being raised in unison to the chanting of Har Har Mahadev — I literally had goosebumps for days after returning. This is a must-do before you leave this world.", days_ago: 10 },
    { name: "Krishnaswamy Pillai", rating: 5, title: "Exactly what a pilgrimage should feel like", content: "76 years old and my first visit to Kashi. MyQuickTrippers arranged a special senior-friendly itinerary — no rush, proper rest breaks, wheelchair accessible routes near the ghats. The guide was patient, respectful, and deeply knowledgeable about Hindu scripture and temple history. Visited 11 temples in 3 days without feeling rushed. Deeply grateful.", days_ago: 18 },
    { name: "Pallavi Singh", rating: 5, title: "The most spiritual 3 days of my life", content: "As someone who isn't deeply religious but is spiritually curious, Varanasi hit me differently than I expected. Our guide Pandit Ramesh ji made us understand the philosophy behind the rituals rather than just watching them as a tourist. The early morning cremation ghat walk is confronting but profoundly moving. MQT's sensitivity to the sacred nature of these places is commendable.", days_ago: 28 },
    { name: "Nikhil Joshi", rating: 4, title: "Incredible experience, summer heat was intense", content: "The package and execution are excellent — MQT's Varanasi coverage is thorough and their boat arrangements are lovely. I'm rating 4 stars purely because we visited in May and the heat was genuinely brutal, with temperatures above 44°C on two days. This obviously has nothing to do with the travel company — just plan your Varanasi visit between October and March for the most comfortable experience. The ghats are equally beautiful in winter.", days_ago: 40 },
    { name: "Ananya Chakraborty", rating: 5, title: "Banarasi silk shopping alone is worth the trip 😂", content: "Okay I went for the spiritual experience and stayed for the shopping — MQT's local guide took us to real Banarasi silk weavers in the old city lanes where prices are honest and craftsmanship is incredible. Also the street food tour they arranged was PHENOMENAL. Kachori sabzi at 6am on the ghats hit different. Would rate 6 stars if I could!", days_ago: 50 },
    { name: "Raghunath Patel", rating: 5, title: "Dev Diwali special package — absolutely stunning", content: "We specifically booked the Dev Diwali package and it was beyond our wildest expectations. 84 ghats lit with lakhs of diyas, fireworks reflection on the Ganga, floating flower lamps — the entire family was moved to tears. MQT secured a premium boat with covered seating which was essential for my elderly parents. Masterclass in event planning.", days_ago: 65 },
    { name: "Meenakshi Sundaram", rating: 5, title: "A journey within a journey", content: "Varanasi is one of those places that doesn't just happen to you — it transforms you. MQT curated an itinerary that balanced spirituality, history and culinary experiences perfectly. The classical music performance they arranged one evening at a heritage haveli was an unexpected and wonderful bonus. This trip will be a reference point in my life.", days_ago: 75 },
    { name: "Tarun Verma", rating: 4, title: "Well organized, accommodation could upgrade slightly", content: "Overall very satisfied with MQT's Varanasi package. The ghat access, boat arrangements, guide quality and food experiences are all excellent. Docking one star because the hotel was slightly far from the main ghats which meant more travel time each morning. A ghat-view property would make this an undeniable 5-star package. The core experience is brilliant though.", days_ago: 88 },
  ],

  "manali-family-4-nights-5-days": [
    { name: "Ramesh Agarwal", rating: 5, title: "Our kids still talk about Manali every dinner 😄", content: "Booked this for our family of 5 (kids aged 8, 12 and 14) and it was the best family vacation we've ever had. Solang Valley's snow activities, Hidimba Devi temple, the old Manali market — perfectly paced for different age groups. MQT's coordinator WhatsApp group made real-time communication seamless. My 8-year-old refuses to eat normal food now — she only wants Maggi the way it tasted at 2500m altitude. 😂", days_ago: 8 },
    { name: "Geeta Bhatt", rating: 5, title: "Family holiday done absolutely right", content: "What I appreciated most about MQT was their attention to children's specific needs. They had snacks ready in the vehicle, the pace of sightseeing was child-friendly, and they arranged skiing lessons for our teenagers at Solang which the kids absolutely loved. The Rohtang Pass excursion was the highlight — kids saw real snow for the first time and the photos are priceless.", days_ago: 20 },
    { name: "Suresh Kumar Yadav", rating: 4, title: "Great trip, Rohtang permit was tricky", content: "The Manali experience with MQT was wonderful. Every logistical detail was handled smoothly. The only complication was a delay in getting Rohtang Pass permits because the NGT had implemented stricter daily limits that week. MQT rearranged our day to Sissu (Lahaul Valley) which was unexpectedly more beautiful and less crowded. Sometimes what seems like a problem turns into a better experience.", days_ago: 35 },
    { name: "Anita Bose", rating: 5, title: "The Beas River view from our room 😍", content: "Our hotel room had a direct view of the Beas River with the Dhauladhar range behind it and I spent a full hour every morning just sitting on the balcony with a cup of chai doing absolutely nothing. That alone was worth the trip. MQT's hotel selection is excellent — clearly chosen for views and location, not just star rating. Adventure activities were perfectly organized too.", days_ago: 42 },
    { name: "Pradeep Chandra", rating: 5, title: "Manali in summer is genuinely spectacular", content: "Been meaning to visit Manali for 15 years and finally made it with MQT. The package covered everything without feeling rushed — apple orchards, local weaving workshops, Naggar Castle, riverside cafes in Old Manali. The van Picard was knowledgeable and funny. Food arrangements were excellent — they found a restaurant that could make proper South Indian breakfast for my wife who isn't a North Indian cuisine person.", days_ago: 55 },
    { name: "Nandita Joshi", rating: 3, title: "Kids loved it but roads are rough", content: "Manali is stunning and MQT's family package is thoughtfully curated. My honest feedback is that the mountain roads in certain sections tested our nerves considerably, especially with young children in the car. This is a geographic reality of Himalayan travel that no tour operator can change, but first-time mountain travellers should be mentally prepared. Our driver was excellent and very reassuring. The destination itself is worth it.", days_ago: 68 },
    { name: "Mohan Tripathi", rating: 5, title: "Summer skiing in Rohtang — bucket list checked!", content: "Didn't expect to see snow in June but MQT made sure we got the full snow experience at Rohtang. The snow activities for kids were safe, supervised and fun. Our guide was experienced in handling first-timers on snow. Back in Delhi now and the kids are already asking to go again next year. A great family bonding experience. Highly recommend MQT for family trips in the hills.", days_ago: 80 },
  ],

  "rishikesh-adventure-2-nights-3-days": [
    { name: "Aakash Mehta", rating: 5, title: "The river rafting section is INSANE in the best way", content: "Grade 3 and 4 rapids on the Ganges near Rishikesh hit different when you're actually in the raft. The MQT safety briefing was thorough, the life jackets were premium quality, and the guides were experienced and communicative throughout. Post-rafting chai by the river bank was somehow the most satisfying chai I've ever had. Bungee jump at Mohan Chatti was bucket-list level terrifying. 10/10.", days_ago: 5 },
    { name: "Shruti Kapoor", rating: 5, title: "Yoga + adventure = perfect combo", content: "I went expecting just the adventure activities and MQT surprised me with an optional sunrise yoga session at Parmarth Niketan which was extraordinary. The combination of white-water rafting energy and morning meditation energy is genuinely therapeutic. Also the Beatles Ashram visit they fit into the schedule was a lovely cultural bonus. Excellent planning.", days_ago: 14 },
    { name: "Kiran Reddy", rating: 5, title: "Corporate team outing — everyone went home happy", content: "Organised this for 12 colleagues and MQT handled a group booking seamlessly. The rafting convoy, the cliff jumping, the camping by the riverside — every activity had proper safety protocols and the energy was fantastic. Even our most cautious colleague did the jump by the end! MQT's group hospitality is excellent. Already planning the next outing.", days_ago: 22 },
    { name: "Varun Saxena", rating: 4, title: "Great adventure, monsoon timing needs thought", content: "The Rishikesh adventure package with MQT is excellent — safety, logistics, guide quality all top-notch. We visited in August during monsoon and while that made the rapids more thrilling, one of the rafting stretches had to be skipped due to water levels being too high for safe navigation. The team substituted with a kayaking session and it was actually more fun. Just flag it if your travel window is monsoon season — the Ganga has her own schedule.", days_ago: 35 },
    { name: "Divya Shankar", rating: 5, title: "Changed my relationship with fear permanently", content: "I have a fear of water and heights but came with my adventure-junkie friends as moral support. By day 2, I had done both the raft and the bungee. MQT's guides created such a supportive environment and never pressured me — they waited patiently and gently encouraged. The personal growth I experienced in 3 days is something I couldn't have gotten in months of therapy. Book this trip for yourself.", days_ago: 48 },
    { name: "Saurabh Tiwari", rating: 5, title: "The camping night by the Ganga is poetic", content: "Among everything MQT scheduled, the overnight camping on the Ganga bank was the experience I'll remember longest. Bonfire, acoustic guitar by a fellow traveller, a sky full of stars without city light pollution, and the constant sound of the river. Morning chai at the campsite while the mist lifted off the river... genuinely poetic. The adventure activities are the marketing, but that night is the real experience.", days_ago: 60 },
  ],

  "kashmir-family-7-nights-8-days": [
    { name: "Rajesh Nambiar", rating: 5, title: "Kashmir is a country inside India", content: "7 nights felt both too long and too short — both at the same time. MQT covered Sonamarg, Pahalgam, Gulmarg and Srinagar with perfect pacing for our 4 kids between 6 and 16. Every child had different energy levels and attention spans but the team kept everyone engaged. The elder kids loved the Gulmarg gondola and the younger ones adored the shikara ride on Dal Lake feeding the ducks. Perfect cross-age family holiday.", days_ago: 12 },
    { name: "Latha Srinivasan", rating: 5, title: "Every photo looks like a postcard", content: "As a photography enthusiast I was blown away by the visual variety that MQT packed into 8 days. Alpine meadows at Sonamarg, the mirror-like Vishansar Lake, the wooden architecture of old Srinagar, the rose gardens, the wicker market, and the floating vegetable market at dawn — MQT clearly knows all the visual gems. My SD card ran out on day 5.", days_ago: 25 },
    { name: "Venkatesan Pillai", rating: 4, title: "Wonderful trip with one weather detour", content: "The 8-day Kashmir family package is extraordinarily well-designed. We had one setback when heavy snowfall blocked the Zoji La pass temporarily on our Sonamarg day. MQT's team had an alternative itinerary ready within an hour — we visited Doodhpathri valley instead which turned out to be gorgeous and completely uncrowded. MQT's crisis handling earns them the 5th star morally, but I'll keep it 4 for transparency.", days_ago: 40 },
    { name: "Mamta Agarwal", rating: 5, title: "My mother-in-law wanted to stay forever 😂", content: "We travelled with my 68-year-old mother-in-law who is generally very hard to please. By day 3 she had declared MQT 'the best company in India' and by day 6 she was refusing to board the return flight. The slow pacing, the comfortable vehicles with cushioned seats, regular chai stops, and the patient guide who answered all her questions — they made an elderly traveller feel genuinely cared for.", days_ago: 52 },
    { name: "Amar Joshi", rating: 5, title: "The houseboat is the entire Kashmir experience", content: "We spent 3 of our 7 nights on the houseboat and it was perfect. Watching the lights of Srinagar reflect on Dal Lake at midnight, waking to the sound of the shikarawallahs, the carved walnut furniture, the kangri warmth — the houseboat is not just accommodation, it's an experience unto itself. MQT's houseboat selection is premium and authentic. Cannot recommend enough.", days_ago: 65 },
    { name: "Sneha Patil", rating: 5, title: "Kashmir changed our family forever", content: "We were a family that never took holidays seriously until this trip. MQT's Kashmir package became the reference point against which our family now evaluates everything. The kids came back more culturally aware, more curious and more grateful. That's the real value of a great travel experience. Thank you MQT for this gift.", days_ago: 78 },
  ],

  "ladakh-luxury-8-nights-9-days": [
    { name: "Kabir Malhotra", rating: 5, title: "Pangong Tso at sunrise — I've run out of adjectives", content: "I've travelled to 31 countries and Pangong Lake at 4350m altitude at 05:30 in the morning is the most otherworldly thing I have ever seen. MQT's luxury package had us camping near the lake with proper heated Swiss tents and a chef who made the most ridiculous gourmet breakfast at altitude. The Leh nightscape from our heritage hotel rooftop was a bonus. This is the pinnacle of Indian travel.", days_ago: 7 },
    { name: "Ishaan Chaudhary", rating: 5, title: "The monastery circuit is deeply moving", content: "MQT paired the adventure of mountain roads with deep cultural visits — Thiksey monastery with its 5:30am butter lamp ceremony, Hemis festival preparations, the ancient murals at Alchi. Our guide was a local Ladakhi scholar who brought these places alive with authentic context rather than rehearsed tourist facts. The luxury accommodation — a converted 200-year-old Ladakhi palace — was exquisite.", days_ago: 20 },
    { name: "Pooja Venkataraman", rating: 4, title: "Altitude sickness hit us unexpectedly", content: "The luxury experience MQT provides in Ladakh is genuine and impressive. My reason for 4 stars is that altitude sickness affected 2 of our group members significantly on day 2, despite following the acclimatisation advice. MQT's response was immediate — they arranged oxygen cylinders, a doctor's consultation and an adjusted itinerary for the affected members. The care they showed was excellent. Just understand that Ladakh's altitude is nature's reality.", days_ago: 35 },
    { name: "Naveen Kumar", rating: 5, title: "Nubra Valley camel safari is not optional 😂", content: "Put it on the itinerary. Trust me. Bactrian double-humped camel safari in the sand dunes of Nubra Valley with the Himalayas as backdrop is something your corporate PowerPoint presentations simply cannot prepare you for. Your brain malfunctions. MQT had a brilliant local photographer capture the group shots and the results are hanging in my living room now. Perfect luxury adventure fusion.", days_ago: 48 },
    { name: "Sharmila Gupta", rating: 5, title: "MQT handled Ladakh logistics like absolute pros", content: "Ladakh's remoteness means a thousand things can go wrong — permit delays, weather closures, fuel shortages. MQT navigated every single one with calm professionalism. When Khardung La was briefly closed due to army convoy movement, our team simply had a backup plan ready. Also the luxury camp at Hunder had warm water, electricity and WiFi at 3000m which genuinely felt like magic.", days_ago: 62 },
    { name: "Deepak Sharma", rating: 5, title: "9 days weren't enough", content: "Returned from Ladakh feeling like I need at least 3 more weeks to do it justice. MQT's luxury package covered the key highlights with genuine depth but Ladakh is so vast and varied that you inevitably want more. The quality of vehicles, accommodation, guides and food is consistently premium throughout. Already discussing next year's Zanskar extension with their team.", days_ago: 75 },
    { name: "Usha Menon", rating: 5, title: "Stars at 4000m altitude are 1000x brighter", content: "I am a retired school headmistress who always thought Ladakh was 'for young adventurers'. MQT convinced me otherwise and they were absolutely right. The terrain is challenging but the luxury package means you do it comfortably. The star-gazing session MQT arranged with a local astronomer at midnight near Pangong is something I would have never organized myself. Outstanding.", days_ago: 90 },
    { name: "Abhinav Tiwari", rating: 4, title: "Slightly overcast during Pangong visit", content: "The overall experience MQT provides in Ladakh is genuinely world-class. My one disappointment was that Pangong Lake was partly overcast during our visit which dimmed the legendary turquoise-blue colour that it usually shows in photographs. This is purely a weather matter — Ladakh's sky does what it wants. On every other parameter, from accommodation to food to guide quality, MQT is outstanding. Would absolutely return.", days_ago: 100 },
  ],

  "char-dham-yatra-10-nights-11-days": [
    { name: "Hari Prasad Sharma", rating: 5, title: "Badrinath darshan at 4am will stay with me forever", content: "At 67, completing Char Dham Yatra has been my life's biggest dream. MQT made it dignified and deeply spiritual rather than just a logistical exercise. The 4am Badrinath darshan with the aarti, the morning mist on the Alaknanda, the silence interrupted only by temple bells — this is what moksha feels like, if only briefly. MQT's team treated us pilgrims with genuine reverence.", days_ago: 9 },
    { name: "Savitri Devi", rating: 5, title: "MQT is a blessing for senior pilgrims", content: "I'm a 71-year-old widow travelling with my daughter. MQT's senior-friendly package had pony arrangements at Kedarnath without any extra complications, a private vehicle throughout, proper vegetarian sattvic meals and emergency medical support. The guides arranged queue priority at temples for senior citizens and helped with ritual procedures at each shrine. This yatra healed my soul.", days_ago: 22 },
    { name: "Prakash Agrawal", rating: 5, title: "11 days of complete spiritual immersion", content: "The Char Dham circuit — Yamunotri, Gangotri, Kedarnath, Badrinath — is not a holiday. It's a pilgrimage in the truest sense. MQT understood this distinction completely. There was no rushing, no commercial tourism mentality. The pacing allowed for genuine prayer and reflection at each dhaam. The team fasted on Ekadashi alongside the pilgrims without being asked. That kind of empathy is rare.", days_ago: 36 },
    { name: "Rajan Mishra", rating: 4, title: "Yamunotri route had some delays due to rainfall", content: "The yatra itself is profoundly meaningful and MQT's organisation is impeccable. We did experience delays on the Yamunotri approach due to heavy Uttarakhand rainfall that created temporary landslide clearance work on the route. The state authorities cleared it within hours but it added significant waiting time. MQT kept everyone calm, provided hot chai and snacks, and handled the delay gracefully. Divine timing has its own schedule.", days_ago: 50 },
    { name: "Sunanda Krishnan", rating: 5, title: "The Ganga at Gangotri — tears that surprised me", content: "I didn't expect to cry at Gangotri. Standing at the source watching the crystal-clear Bhagirathi emerge from under the glacier, reciting prayers my grandmother taught me decades ago — emotions I didn't know were stored in me came flooding out. This is why Char Dham Yatra exists. MQT created the conditions for this to happen with their respectful and patient approach to travel.", days_ago: 65 },
    { name: "Govind Patel", rating: 5, title: "Helicopter upgrade at Kedarnath was life-changing", content: "At 75, I genuinely wasn't sure if my knees could handle Kedarnath. MQT seamlessly arranged a helicopter upgrade for just that leg of the journey and the Kedarnath shrine seen from the helicopter against the Himalayas is an image I can't describe. The darshan itself was peaceful and private. MQT's flexibility and care for elderly pilgrims is genuinely extraordinary.", days_ago: 78 },
  ],

  "kedarnath-helicopter-2-nights-3-days": [
    { name: "Amit Trivedi", rating: 5, title: "Kedar Baba ki jai! What a darshan!", content: "The helicopter experience saves so much physical effort that it allows you to arrive at Kedarnath fresh and completely present for the darshan rather than exhausted and depleted. MQT's helicopter arrangement was smooth — the pilot was experienced, the 15-minute flight over the Mandakini valley is stupendously beautiful, and the darshan timing they arranged was peaceful without the usual crowd crush. Jai Kedarnath!", days_ago: 6 },
    { name: "Parvati Iyer", rating: 5, title: "A darshan that answered every prayer", content: "Travel outside Kedarnath temple at 5:30am before the tourist crowds arrive and look back at the temple against the Himalayan skyline. That is the image MQT gave me access to through their early-morning darshan slot. The puja arrangements they facilitated through the temple trust were elaborate and personal. This trip changed something fundamental in me.", days_ago: 18 },
    { name: "Shankar Rao", rating: 5, title: "Helicopter view of Himalayan range is incredible", content: "Even if you have done Kedarnath on foot before, the helicopter approach gives you a completely different perspective — the scale of the Himalayas, the tiny thread of the pilgrimage route visible far below, the snow-covered peaks stretching to the horizon. MQT's coordination was flawless and their helicopter partner had a perfect safety record. Everything on time, everything clear.", days_ago: 30 },
    { name: "Nirmala Devi", rating: 4, title: "Divine experience, helicopter had 30-min delay", content: "The Kedarnath darshan itself is beyond rating — it simply is. MQT's overall package quality is excellent. The helicopter had a 30-minute departure delay on our return leg due to air traffic management from other operators sharing the corridor. Nothing unusual in a high-traffic pilgrimage season and MQT kept us informed throughout. The darshan makes every small inconvenience completely irrelevant.", days_ago: 45 },
    { name: "Kunal Sharma", rating: 5, title: "Worth every rupee and more", content: "My father had been wanting to do Kedarnath for 20 years but his knee replacement made the 18km trek impossible. The helicopter package MQT offered was his answer. Watching my 72-year-old father bow before Kedarnath Jyotirlinga is the most emotional thing I've experienced. MQT made an impossible dream possible. I cannot thank them enough.", days_ago: 55 },
    { name: "Radha Kumari", rating: 5, title: "The Mandakini river from above is a ribbon of gold", content: "I'd expected impressive scenery but nothing prepared me for the view from the helicopter window — the Mandakini river winding silver through the dark valley, prayer flags marking the high ridges, the enormous amphitheatre of the Himalayan peaks surrounding the tiny but radiant temple. MQT's choice of early morning flight timing gives you the best light. Absolute masterpiece.", days_ago: 70 },
  ],

  "manali-winter-snow-4-nights-5-days": [
    { name: "Rohit Kumar Sinha", rating: 5, title: "Delhi to Manali and suddenly it's Narnia", content: "I've been to Manali in summer but winter is a completely different planet. MQT's winter package had snow-proof jackets ready (ours weren't adequate), proper hiking boots, hand warmers, and hotel rooms with in-built heating that actually worked. Solang Valley in full snowfall with nobody else around except your group is an experience that makes urban stress feel very small.", days_ago: 8 },
    { name: "Komal Sharma", rating: 5, title: "Ski lessons were the highlight of 2024 for me", content: "Never skied in my life. MQT's winter package included beginner ski lessons with a certified instructor at Solang. By hour 3, I was independently managing the nursery slope. By day 2, I did a proper blue run. The instructor was patient and the safety equipment was good quality. This is the hidden gem of the Manali winter package — you come back with a new skill.", days_ago: 19 },
    { name: "Narendra Verma", rating: 4, title: "Magical but roads deserve a mention", content: "The winter Manali experience with MQT is genuinely magical — snow-laden deodar trees, the frozen Beas banks, the smoky mountain cafes with momos and hot chocolate. My one flag is that the Manali-Rohtang stretch in winter requires very experienced mountain drivers, and while MQT's driver was excellent, first-timers should mentally prepare for steep, icy switchbacks. The scenery compensates spectacularly.", days_ago: 32 },
    { name: "Seema Tandon", rating: 5, title: "Snow selfies that break Instagram 📸", content: "Not going to lie, a significant portion of the trip was photographic in nature 😂 But the point is MQT took us to locations that most tourists never find — a small frozen lake off the main highway, a viewpoint where the Beas Valley spreads beneath you uninterrupted, a local Himachali home for authentic Dham meal. The instagram photos are bonus, the memories are priceless.", days_ago: 44 },
    { name: "Manjunath Hegde", rating: 5, title: "Winter Manali deserves its own reputation", content: "Summer Manali is crowded and commercial. Winter Manali is serene, local, and dramatically beautiful. MQT clearly understands this distinction and their winter package leans into the quietness rather than trying to replicate the summer rush. The hotel had a fireplace lounge where we spent evenings playing cards, drinking Himachali chai and watching snow fall outside. I was in no hurry to return.", days_ago: 58 },
  ],

  "kashmir-solo-4-nights-5-days": [
    { name: "Anjali Krishnan", rating: 5, title: "Solo female travel in Kashmir — completely safe with MQT", content: "The biggest fear around Kashmir solo travel — especially for women — is safety. I want to categorically state that I felt safer in Kashmir than I do in my own city. Locals are extraordinarily welcoming and MQT's female-friendly safety protocols are excellent. My coordinator checked in twice daily and the local guide was professional and boundary-respecting throughout. Kashmir is waiting. Go.", days_ago: 11 },
    { name: "Yash Mehta", rating: 5, title: "When you need to disappear from the world, go to Kashmir", content: "After a rough year personally, I booked this solo package on impulse. Five days in Kashmir with MQT's thoughtful solo itinerary — solo shikara rides at dusk, wandering the old city's lanes alone, sitting by the Lidder river in Pahalgam with a book — was genuinely therapeutic. The travel industry talks about wellness travel but rarely delivers it. MQT does.", days_ago: 25 },
    { name: "Priya Ramachandran", rating: 5, title: "The old Srinagar lanes are a living museum", content: "MQT's solo package gave me the freedom to explore at my own pace, which is all a solo traveller really wants. Their recommendations of off-beat areas like the Jewish Quarter of old Srinagar, the Sufiana Kalam musical tradition, and the papier-mâché artist workshops were extraordinary cultural experiences that no group tour would have had time for. Deeply satisfied.", days_ago: 38 },
    { name: "Rahul Pandey", rating: 4, title: "Dal Lake houseboat solo — slightly lonely at dinner", content: "The solo Kashmir package is excellent and MQT's planning is thorough. My honest feedback is that the houseboat experience is designed more for couples/families and solo dining on the boat each evening felt slightly solitary. A minor thing that could be improved — perhaps connecting solo travellers for one evening meal. This didn't significantly impact the trip which was wonderful overall.", days_ago: 52 },
    { name: "Kriti Malhotra", rating: 5, title: "I travelled alone and never felt alone", content: "MQT seems to understand that solo travel isn't about being lonely. My guide introduced me to local Kashmiri artisans, a university professor who spoke fascinating things about Kashmir's history, and a group of trekkers I ended up hiking with for a day. The connections MQT's team facilitates organically are the invisible value-add of this package. Outstanding.", days_ago: 66 },
    { name: "Aryan Gupta", rating: 5, title: "Took myself on a solo date to Kashmir 💛", content: "Okay dramatic headline but genuinely — solo travel with MQT is an incredible act of self-care. No compromising on what you want to see, no waiting for others, no group politics. Your day, your pace, your wishes. MQT's coordination works even better solo because the entire team's attention is on just you. Returned from Kashmir feeling completely restored.", days_ago: 80 },
  ],

  "varanasi-prayagraj-4-nights-5-days": [
    { name: "Lalita Devi", rating: 5, title: "Triveni Sangam darshan was life-completing", content: "As a 74-year-old devotee, taking the holy dip at Triveni Sangam in Prayagraj during this pilgrimage was the most spiritually significant moment of my life. MQT arranged early morning access, proper ghat descent assistance for elderly pilgrims, clean change facilities and post-bath warm food. They understand the sacredness of the experience and handle it accordingly.", days_ago: 14 },
    { name: "Dinesh Chaturvedi", rating: 5, title: "Two sacred cities, one perfect package", content: "Combining Varanasi and Prayagraj in a single itinerary makes complete spiritual and geographic sense and MQT executes this combination masterfully. The Kashi Vishwanath corridor visit, the Prayagraj fort's Akbar-era architecture, the Ganga Aarti, the Sangam boat — every piece fits together like a well-composed raga. Excellent pacing, zero unnecessary rushing.", days_ago: 27 },
    { name: "Rekha Pandey", rating: 5, title: "My mother's last wish — MQT made it happen with grace", content: "My 80-year-old mother had one wish before she passed from this world — to see the Triveni Sangam. She is bedridden and we thought it impossible. MQT arranged a specially equipped vehicle, a wheelchair, and a small boat that could accommodate the chair at the sangam ghat. My mother dipped her palms in the sacred waters. She beams every time we talk about it. There are no words for MQT's care.", days_ago: 45 },
    { name: "Vikrant Singh", rating: 4, title: "Prayagraj roads during peak season — patience needed", content: "The spiritual experience of both cities is profound and MQT's itinerary is thoughtfully designed. During peak pilgrimage season, the road congestion in Prayagraj city can add 60-90 minutes to transfers. This is an inherent city-level infrastructure reality and not something MQT can solve. Their drivers navigated it calmly and used the waiting time to share interesting local history. The destinations are worth the patience.", days_ago: 60 },
    { name: "Padmavathi Nair", rating: 5, title: "Two of the holiest cities — perfectly connected", content: "I was nervous about fitting two significant pilgrimage cities in 5 days without it feeling rushed. MQT's pacing was exactly right — 2.5 days each city with morning and evening slots used intelligently. The Ganga Aarti in Varanasi and the morning Sangam prayer in Prayagraj are the twin peaks, and everything else flows beautifully around them. Jai Jai Ganga Maiyya.", days_ago: 75 },
  ],

  "himalayan-grand-circuit-12-nights-13-days": [
    { name: "Siddharth Rao", rating: 5, title: "13 days and I could have stayed 13 months", content: "The Himalayan Grand Circuit is MQT's magnum opus. Shimla's colonial charm, Kinnaur's apple orchards and ancient Buddhist temples, Spiti's otherworldly barren plateau, Manali's green valleys — each environment is completely different from the previous. The continuous transition through microclimates and cultures is an extraordinary privilege. MQT stitches it together seamlessly.", days_ago: 10 },
    { name: "Vandana Tripathi", rating: 5, title: "Spiti Valley literally looks like Mars", content: "I've scrolled past photos of Spiti Valley for years thinking they were digitally enhanced. They are not. The ochre-brown valley with white-capped peaks and a turquoise river at its base looks exactly like that in real life. MQT's circuit goes deeper into Spiti than most packages — we reached villages that get tourists perhaps a few dozen times a year. Those interactions were humbling and beautiful.", days_ago: 24 },
    { name: "Nihar Patel", rating: 5, title: "Key Monastery dawn prayer — unforgettable", content: "MQT arranged for our group to attend the early morning prayer (puja) at Key Monastery — an 11th century Tibetan Buddhist monastery perched dramatically on a cliff at 4150m. The resident monks' deep chanting resonating in the ancient stone halls as the first light touched the Spiti Valley through the window — this is the kind of experience that travel companies rarely arrange and that money can't fully recreate.", days_ago: 38 },
    { name: "Abhishek Nair", rating: 4, title: "Spiti roads — be mentally prepared", content: "This is not a gentle holiday. The Himalayan circuit involves some genuinely challenging high-altitude mountain roads where there is no guardrail on one side and a 500m drop on the other. MQT's drivers are exceptional — experienced, careful, and calm — but the geography is what it is. If you have very young children or severe anxiety about heights/narrow mountain roads, make an informed decision. For adventurous adults, this is ultimately thrilling rather than frightening.", days_ago: 52 },
    { name: "Tejaswini Kulkarni", rating: 5, title: "Kinnaur's apple orchards in September 🍎", content: "MQT timed our Kinnaur transit to coincide with apple harvest season and the result was extraordinary — miles of orchards heavy with red and golden apples, local families harvesting, fresh apple juice straight from the press, and crisp autumn mountain air. These micro-moments of local life that MQT creates access to are what elevate their packages above standard tour company offerings.", days_ago: 65 },
    { name: "Manohar Lal", rating: 5, title: "At 65, the Grand Circuit remained accessible", content: "My wife and I were worried that 13 days of high-altitude travel would be too demanding. MQT designed the itinerary with proper acclimatisation days built in, altitude-appropriate dietary recommendations, and flexibility for adjusted pacing if needed. We completed every segment comfortably. The circuit is genuinely grand and MQT makes it genuinely accessible.", days_ago: 80 },
    { name: "Charulata Ghosh", rating: 5, title: "My most ambitious trip and my most satisfying", content: "Planned this for 2 years, finally did it with MQT. The 13-day investment returns experiences that last a lifetime. Chandratal Lake's mirror surface at 4300m, Kibber village's painted whitewashed homes against lunar landscape, the Sangla Valley's apple blossom — each day is a completely new world. MQT's local guides in each region bring granular cultural depth. This is a masterclass in Himalayan travel.", days_ago: 95 },
  ],

  "kedarnath-yatra-5-nights-6-days": [
    { name: "Balram Shukla", rating: 5, title: "Kedarnath is where atheists become believers", content: "I say this as someone who was genuinely sceptical about pilgrimage travel. Standing before the Kedarnath Jyotirlinga with the Himalayan massif as backdrop and the sound of the Mandakini below — something shifts in you that you cannot rationally explain. MQT's 6-day yatra package gives you enough time to sink into the experience rather than rush through it. Jai Bhole ki.", days_ago: 8 },
    { name: "Sarla Gupta", rating: 5, title: "The 18km trek with MQT support was manageable", content: "At 58, with moderate fitness, I completed the full 18km trek to Kedarnath temple. MQT's support was comprehensive — pony option available, porters for luggage, medical kit, regular check-ins from the guide, and chai breaks at perfect intervals. The team celebrated with us at the summit. That shared joy between travellers and their team is what makes this company special.", days_ago: 20 },
    { name: "Ramkrishna Iyer", rating: 5, title: "Gaurikund to Kedarnath — the journey IS the pilgrimage", content: "Many pilgrims rush to reach the temple and forget the journey. MQT's guide beautifully explained that the walk itself — through Himalayan forests, past cascading streams, through dense mist — IS the spiritual preparation for the darshan. That philosophy transformed our trek from an exercise into a meditation. The darshan at the end, with those 18km of preparation, hits completely differently.", days_ago: 33 },
    { name: "Uma Shankar", rating: 4, title: "Trail crowded due to peak season timing", content: "MQT's package quality is excellent throughout. Our yatra unfortunately coincided with a major festival weekend which meant the Kedarnath trail was unusually congested on day 3. This is pilgrimage season reality — hundreds of thousands of devotees share limited trail space and it creates bottlenecks. MQT managed our group pacing expertly to avoid the worst crowds but some waiting was inevitable. A scheduling nuance to note when booking.", days_ago: 48 },
    { name: "Shanti Devi", rating: 5, title: "I touched the Shivalinga after dreaming of it for 30 years", content: "30 years of dreaming, 18km of walking, and then — the Shivalinga. MQT made this possible for a 63-year-old grandmother who was told by doctors to avoid strenuous treks. Their team worked with my physician to design a modified approach with adequate rest, pony support and oxygen monitoring. When I finally placed my palms on the Shivalinga, I felt 30 years of prayers converge into that moment. Thank you MQT.", days_ago: 62 },
    { name: "Chetan Bhatt", rating: 5, title: "Sunrise from the Kedarnath temple peak — absolute silence", content: "MQT arranged a very early start to reach Kedarnath before the main crowd arrived. Sitting near the temple at 5am watching the sun slowly illuminate the surrounding peaks in gradients of gold and pink — with absolute silence except for the river — is the most peaceful I have felt in years. Urban Indians need this silence. MQT delivers it.", days_ago: 77 },
    { name: "Premlata Joshi", rating: 5, title: "Family pilgrimage with three generations", content: "My 80-year-old mother, my 55-year-old self, and my 25-year-old daughter — three generations completing Kedarnath Yatra together is something our family will talk about forever. MQT customised the pacing for three different fitness levels simultaneously. My mother had a pony, my daughter trekked, I did a combination. MQT's flexibility across generations is remarkable. Three happy customers, one perfect trip.", days_ago: 88 },
  ],

  "ladakh-adventure-7-nights-8-days": [
    { name: "Vicky Malhotra", rating: 5, title: "Manali-Leh highway — this road will make you believe in roads", content: "The Manali-Leh highway is not just a road — it is one of the world's great journeys. MQT does this route over 2 days which is the correct way — stopping at Jispa, Keylong, Baralacha La, and Pang. The landscape changes every hour and each change is more dramatic than the last. By the time you reach Leh you feel you've traversed several countries in 2 days.", days_ago: 12 },
    { name: "Simran Bedi", rating: 5, title: "Magnetic Hill is genuinely disorienting 😂", content: "We spent 20 minutes at Magnetic Hill convinced that our car was rolling uphill by itself. The guide's explanation of the optical illusion geology made us feel equally foolish and educated simultaneously. MQT fit in 11 major experiences across 8 days without any feeling of rushing — Pangong, Nubra, Khardung La, monasteries, local cuisine, everything. This is their strongest destination.", days_ago: 22 },
    { name: "Rajeev Anand", rating: 5, title: "The Khardung La summit photo is now my laptop wallpaper", content: "World's highest motorable road at 18,380 feet. Standing at the summit marker with a thin, cold wind blowing and the entire Himalayan vista stretched in both directions — you feel very small and very alive simultaneously. MQT times the visit for clear weather windows based on local contacts' forecasts. Our visit was perfectly clear. That summit photo has been commented on by everyone who sees it.", days_ago: 34 },
    { name: "Mamata Ray", rating: 4, title: "Altitude hit harder than expected — MQT handled it well", content: "I want to be honest for future travellers: I experienced significant altitude sickness on day 1 in Leh despite following the acclimatisation advice. MQT's response was immediate and caring — a doctor within 2 hours, supplemental oxygen, complete rest day with adjusted itinerary. I recovered by day 2 and completed most of the pack. Their medical preparedness is genuinely superior. The altitude is Ladakh's reality, not MQT's responsibility.", days_ago: 47 },
    { name: "Sandeep Goyal", rating: 5, title: "Trekking to Stok Kangri base camp was the personal Everest", content: "MQT's adventure package includes an optional high-altitude trek to Stok Kangri base camp at 5150m. I chose this option and it remains the most physically demanding and emotionally rewarding thing I have ever done. The guide pushed me gently beyond what I thought were my limits. The view from base camp looking down at the Indus valley and Leh city is a perspective shift that permanently changes how you see your life.", days_ago: 60 },
    { name: "Tara Singh", rating: 5, title: "Summer in Ladakh — cold air, hot memories", content: "Even in peak summer Ladakh is cold at altitude (8-10°C in the mountains at night) and MQT's packing list was accurate and essential. The adventure package's kayaking on the Indus River was an unexpected delight — bright turquoise water, ancient valley walls, absolute silence. Their village homestay experience in Nimmu was authentic and gave us direct access to local Ladakhi family culture. Brilliant experience.", days_ago: 73 },
    { name: "Leela Krishnan", rating: 5, title: "Took my engineering friends — engineers don't cry but Pangong made them", content: "7 analytical, data-driven engineers who mock emotion went to Ladakh. By day 4 at Pangong Lake, 3 of them were quietly crying looking at the landscape. MQT didn't need to do anything special — they just got us there. The landscape did the rest. That's the test of a great travel company — they take you somewhere that does the work itself.", days_ago: 85 },
  ],
};

// ─── Helper: random date in past N days ──────────────────────────────────
function pastDate(days) {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

// ─── Helper: generate a fake UUID ────────────────────────────────────────
function uuid() {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    return (c === "x" ? r : (r & 0x3) | 0x8).toString(16);
  });
}

// ─── Main seeder ─────────────────────────────────────────────────────────
async function main() {
  console.log("🌱 MQT Review Seeder starting...\n");

  let totalInserted = 0;
  let totalSkipped = 0;

  for (const pkg of PACKAGES) {
    const reviews = REVIEWS[pkg.slug];
    if (!reviews) {
      console.log(`  ⏭ No reviews defined for: ${pkg.slug}`);
      continue;
    }

    console.log(`\n📦 ${pkg.title}`);

    for (const review of reviews) {
      const emailSeed = review.name.toLowerCase().replace(/\s+/g, ".") + "." + Math.floor(Math.random() * 99999) + "@mqt-verified.in";

      // 1. Create real auth user (triggers profile creation)
      const { data: authData, error: authError } = await sb.auth.admin.createUser({
        email: emailSeed,
        password: "TempPassword123!",
        email_confirm: true,
        user_metadata: {
          full_name: review.name,
          avatar_url: avatar(review.name)
        }
      });

      if (authError) {
        console.log(`  ⚠ Auth user creation failed for ${review.name}: ${authError.message}`);
        totalSkipped++;
        continue;
      }

      const userId = authData.user.id;

      // Small delay to ensure the database trigger creates the profile
      await new Promise((r) => setTimeout(r, 800));

      // 2. Insert review using the actual user ID
      const { error: reviewError } = await sb.from("reviews").insert({
        profile_id: userId,
        package_id: pkg.id,
        rating: review.rating,
        title: review.title,
        content: review.content,
        is_verified_booking: true,
        helpful_votes: Math.floor(Math.random() * 45) + 5,
        status: "approved",
        created_at: pastDate(review.days_ago),
        updated_at: pastDate(review.days_ago),
      });

      if (reviewError) {
        console.log(`  ✗ Review failed for ${review.name}: ${reviewError.message}`);
        totalSkipped++;
      } else {
        console.log(`  ✓ ${review.name} → ${"★".repeat(review.rating)} "${review.title.slice(0, 50)}..."`);
        totalInserted++;
      }
    }
  }

  console.log(`\n${"─".repeat(50)}`);
  console.log(`✅ Done! Inserted: ${totalInserted} reviews | Skipped: ${totalSkipped}`);
  console.log("─".repeat(50));
  console.log("\nGo check your Supabase Reviews table 🎉");
}

main().catch(console.error);
